### PR TITLE
RHBPMS-4843: Update standalone controller and smart router images to v7.0.0.ER1

### PR DESCRIPTION
**Pull request by rbarriuso**

### CODE REVIEW

**Comment by rbarriuso** [comment]
See https://github.com/jboss-container-images/jboss-bpmsuite-7-image/pull/8 too

**Comment by psiroky** [comment]
Thanks @rbarriuso! 

I am wondering about one thing. Could we directly use the `jboss-bpmsuite-7.0-execution-server-controller-ee7.zip`? Currently the build downloads 400MiB of data in the -collection.zip, but we only need the zip which has 21MiB. This should also slightly speed up the build (if that matters). WDYT?

**Comment by rbarriuso** [comment]
I'm not sure if the `jboss-bpmsuite-7.0-execution-server-controller-ee7.zip` artifact is part of the official delivery. What do you think, @goldmann ?

**Comment by goldmann** [comment]
This is hard to answer. You need to ask the PM what bits will be released. This is outside of my control. Obviously I suggest using artifacts that are going to be published at the release time.

**Comment by errantepiphany** [comment]
@psiroky @rbarriuso @goldmann I think we can move forward with this PR as is, and open a new one if we can we decide to change to a different zip.

**Review by errantepiphany — APPROVED** [review]

**Review by errantepiphany — APPROVED** [review]
Changes look good.

**Review by goldmann — APPROVED** [review]

**Pull request merged**
