### PR TITLE
Moved to concreate

### PR DESCRIPTION
**Pull request by rwngwn**
Signed-off-by: David Becvarik <dbecvari@redhat.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for other issues
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Comment by goldmann** [comment]
@errantepiphany @psiroky FYI - we need to merge this - we're moving to Concreate: https://github.com/jboss-container-images/concreate

**Comment by errantepiphany** [comment]
@goldmann, is there an associated PR in jboss-bpmsuite-7-openshift-image?

**Comment by goldmann** [comment]
There will be one, we're working on this.

**Review by errantepiphany — APPROVED** [review]
Looks good.

**Review by goldmann — APPROVED** [review]

**Pull request merged**
