### PR TITLE
CLOUD-2015 add product labels

### PR DESCRIPTION
**Pull request by bdecoste**
Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for other issues
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Comment by goldmann** [comment]
FYI @AntStephenson

**Comment by goldmann** [comment]
@ryanzhang

**Review by antncl — APPROVED** [review]

**Comment by antncl** [comment]
@goldmann changes look good to me. But I don't have permissions to merge.

**Comment by goldmann** [comment]
It was more a FYI, since we need to move with these changes. I'm happy to merge it.

**Comment by antncl** [comment]
Ah, just when you CC'd Ryan just now, I wondered if there was any action required from us :) Thanks for the heads up!

**Comment by goldmann** [comment]
Not really, just wondered when is the best time to merge it (hint: CR1).

**Review by goldmann — APPROVED** [review]

**Pull request merged**
